### ISSUE TITLE
Error TOOLTIP

### ISSUE THREAD

**Issue by Nowi5** [summernote/awesome-summernote#67]
Hi,

with the latest version of summernote 0.8.10 the tooltip seems to have a bug
Error: TOOLTIP: Option "container" provided type "undefined" but expected type "(string|element|boolean)"

Maybe also a conflict with other AdminLTE3 packages
![grafik](https://user-images.githubusercontent.com/27913135/45059336-f31d4000-b09b-11e8-9c9d-d151182626fc.png)

**Comment by DennisSuitters** [comment]
You would get more attention creating this issue on the main project repository.

**Comment by Nowi5** [comment]
Ture but the main package is working fine, your extension does not.

**Comment by DennisSuitters** [comment]
This repository is for access to plugins, a list of sorts. Issues like what you are reporting would get more notice to have them fixed by creating the issue on the main project repository. Someone outside of the project may also even have a fix for it, or if you know how to fix the issue, your welcome to create a PR.
